name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: androidApp

  # The name of the Play Store
  playstore_name: ESMira

on:

  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Android version
        id: androidApp
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: androidApp/build.gradle.kts 
      
      - name: Check if release exists
        id: check-release-exists
        shell: bash
        run: |
          priorRelease=$(gh release list --limit 1 --json tagName --jq .[0].tagName)
          echo "Prior release: $priorRelease"
          if [[ "$priorRelease" == "v${{steps.androidApp.outputs.versionName}}" ]]; then
            echo "Release 'v${{steps.androidApp.outputs.versionName}}' already exists."
            echo "ReleaseExists=true" >> $GITHUB_OUTPUT
          else
            echo "Release 'v${{steps.androidApp.outputs.versionName}}' not found."
            echo "ReleaseExists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Set Up JDK
        if: ${{steps.check-release-exists.outputs.ReleaseExists == 'false'}}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
#      - name: Run gradle tests
#        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        if: ${{steps.check-release-exists.outputs.ReleaseExists == 'false'}}
        run: ./gradlew ${{ env.main_project_module }}:build -x lint 

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        if: ${{steps.check-release-exists.outputs.ReleaseExists == 'false'}}
        run: ./gradlew assemble

      # Create Bundle AAB Release
      # Noted for main module build [main_project_module]:bundleRelease
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        if: ${{steps.check-release-exists.outputs.ReleaseExists == 'false'}}
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Create Release
      - name: Create named release
        if: ${{steps.check-release-exists.outputs.ReleaseExists == 'false'}}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release version ${{steps.androidApp.outputs.versionName}}
          tag_name: v${{steps.androidApp.outputs.versionName}}
          generate_release_notes: true
          append_body: true
          files: |
            ${{ env.main_project_module }}/build/outputs/apk/release/
            ${{ env.main_project_module }}/build/outputs/bundle/release/
